version: '3.7'

services:
  database:
    image: mysql:8
    container_name: 'db_container'
    restart: unless-stopped
    env_file: ./api/.env
    network_mode: 'host'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api_db
      MYSQL_USER: Emir
      MYSQL_PASSWORD: Emir123
    volumes:
      - db:/var/lib/mysql

  api:
    depends_on:
      - database
    build: ./api
    container_name: 'api_container'
    restart: unless-stopped
    network_mode: 'host'
    env_file: ./api/.env
    environment:
      DB_HOST: database
      DB_USERNAME: Emir
      DB_PASSWORD: Emir123
      DB_DATABASE: api_db
    volumes:
      - logs:/app/logs
      - ./api:/app
      - /app/node_modules
    stdin_open: true
    tty: true
  # frontend:
  #   depends_on:
  #     - backend
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true
  #   tty: true

volumes:
  db:
  logs:
