version: '3.9'

networks:
  default:
    driver: bridge

services:
  database:
    image: mysql:8
    container_name: 'db_container'
    restart: on-failure
    expose:
      - '3306'
    # env_file: ./api/.env
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: api_db
      MYSQL_USER: emir
      MYSQL_PASSWORD: test123
    volumes:
      - db:/var/lib/mysql
    networks:
      - default
    ports:
      - '3306:3306'
    # healthcheck:
    #   test: mysqladmin ping -h localhost --user=$$MYSQL_USER --password=$$MYSQL_ROOT_PASSWORD
    #   interval: 30s
    #   timeout: 12s
    #   retries: 10
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD',
        ]
      interval: 5s
      timeout: 20s
      retries: 30

  api:
    build: ./api
    container_name: 'api_container'
    restart: on-failure
    env_file: ./api/.env
    environment:
      DB_HOST: database
      DB_USERNAME: emir
      DB_PASSWORD: test123
      DB_DATABASE: api_db
    volumes:
      - logs:/app/logs
      - ./api:/app
      - /app/node_modules
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    ports:
      - '3100:3100'
  # frontend:
  #   depends_on:
  #     - backend
  #   build: ./frontend
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend/src:/app/src
  #   stdin_open: true
  #   tty: true

volumes:
  db:
  logs:
